from random import choices
PROB_ENCONTRAR_ITEM = 0.5
PROB_ENCONTRAR_TESORO = 0.5
PROB_ENCONTRAR_CONSUMIBLE = 0.5
FELICIDAD_ADICIONAL_DOCENCIO = 1
FUERZA_ADICIONAL_DOCENCIO = 1
ENERGIA_PERDIDA_DOCENCIO = 7
ENERGIA_ADICIONAL_TAREO = 5
SUERTE_ADICIONAL_TAREO = 5
EDAD_ADICIONAL_TAREO = 5
FELICIDAD_PERDIDA_TAREO = 1
POND_ARENA_NORMAL = .7
PROB_LLUVIA = .3
PROB_TERREMOTO = .5
PROB_DERRUMBE = .2
PROB_INICIAR_EVENTO = .3
METROS_PERDIDOS_DERRUMBE = 10
DIAS_TOTALES_TORNEO = 7
ARENA_INICIAL = "normal"
EXCAVADORES_INICIALES = 3
METROS_META = 100


