ANCHO_GRILLA = 11 # NO EDITAR
LARGO_GRILLA = 16 # NO EDITAR

# Complete con los demás parámetros

MIN_CARACTERES = 6
MAX_CARACTERES = 16
CANTIDAD_VIDAS = 3

MAXIMO_FANTASMAS_HORIZONTAL = 3
MAXIMO_FANTASMAS_VERTICAL = 3
MAXIMO_FUEGO = 8
MAXIMO_ROCA = 3
MAXIMO_PARED = 7

MIN_VELOCIDAD =7
MAX_VELOCIDAD = 9

TIEMPO_CUENTA_REGRESIVA = 60
MULTIPLICADOR_PUNTAJE =  2