ANCHO_GRILLA = 11 # NO EDITAR
LARGO_GRILLA = 16 # NO EDITAR

# Complete con los demás parámetros

MIN_CARACTERES = 6
MAX_CARACTERES = 16
CANTIDAD_VIDAS = 3

FANTASMAS_HORIZONTALES = 3
FANTASMAS_VERTICALES = 3
FUEGOS = 3
ROCAS = 3
MURALLAS = 3

MIN_VELOCIDAD = 3
MAX_VELOCIDAD = 1